[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
actix-rt = "1.0.0"
actix-web = { version = "2.0.0", default-features = false }
http = "0.2.1"
bottlerocket-release = { path = "../../bottlerocket-release" }
futures = { version = "0.3", default-features = false }
libc = "0.2"
log = "0.4"
models = { path = "../../models" }
nix = "0.17.0"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.7"
snafu = "0.6"
walkdir = "2.2"
thar-be-updates = { path = "../thar-be-updates"}
update_metadata = { path = "../../updater/update_metadata"}
semver = "0.9"
num = "0.3.0"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
toml = "0.5"
